/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMailboxesRouteImport } from './routes/_authenticated/mailboxes'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDomainsIndexRouteImport } from './routes/_authenticated/domains.index'
import { Route as ApiPublicAgentPingRouteImport } from './routes/api/public/agent/ping'
import { Route as ApiPublicAgentEmailsRouteImport } from './routes/api/public/agent/emails'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMailboxesRoute = AuthenticatedMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsIndexRoute =
  AuthenticatedDomainsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDomainsRoute,
  } as any)
const ApiPublicAgentPingRoute = ApiPublicAgentPingRouteImport.update({
  id: '/api/public/agent/ping',
  path: '/api/public/agent/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentEmailsRoute = ApiPublicAgentEmailsRouteImport.update({
  id: '/api/public/agent/emails',
  path: '/api/public/agent/emails',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/mailboxes': typeof AuthenticatedMailboxesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/domains/': typeof AuthenticatedDomainsIndexRoute
  '/api/public/agent/emails': typeof ApiPublicAgentEmailsRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/mailboxes': typeof AuthenticatedMailboxesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/domains': typeof AuthenticatedDomainsIndexRoute
  '/api/public/agent/emails': typeof ApiPublicAgentEmailsRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/mailboxes': typeof AuthenticatedMailboxesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/domains/': typeof AuthenticatedDomainsIndexRoute
  '/api/public/agent/emails': typeof ApiPublicAgentEmailsRoute
  '/api/public/agent/ping': typeof ApiPublicAgentPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/domains'
    | '/inbox'
    | '/mailboxes'
    | '/settings'
    | '/domains/'
    | '/api/public/agent/emails'
    | '/api/public/agent/ping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/inbox'
    | '/mailboxes'
    | '/settings'
    | '/domains'
    | '/api/public/agent/emails'
    | '/api/public/agent/ping'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/domains'
    | '/_authenticated/inbox'
    | '/_authenticated/mailboxes'
    | '/_authenticated/settings'
    | '/_authenticated/domains/'
    | '/api/public/agent/emails'
    | '/api/public/agent/ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgentEmailsRoute: typeof ApiPublicAgentEmailsRoute
  ApiPublicAgentPingRoute: typeof ApiPublicAgentPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mailboxes': {
      id: '/_authenticated/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof AuthenticatedMailboxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains/': {
      id: '/_authenticated/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof AuthenticatedDomainsIndexRouteImport
      parentRoute: typeof AuthenticatedDomainsRoute
    }
    '/api/public/agent/ping': {
      id: '/api/public/agent/ping'
      path: '/api/public/agent/ping'
      fullPath: '/api/public/agent/ping'
      preLoaderRoute: typeof ApiPublicAgentPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/emails': {
      id: '/api/public/agent/emails'
      path: '/api/public/agent/emails'
      fullPath: '/api/public/agent/emails'
      preLoaderRoute: typeof ApiPublicAgentEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDomainsRouteChildren {
  AuthenticatedDomainsIndexRoute: typeof AuthenticatedDomainsIndexRoute
}

const AuthenticatedDomainsRouteChildren: AuthenticatedDomainsRouteChildren = {
  AuthenticatedDomainsIndexRoute: AuthenticatedDomainsIndexRoute,
}

const AuthenticatedDomainsRouteWithChildren =
  AuthenticatedDomainsRoute._addFileChildren(AuthenticatedDomainsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMailboxesRoute: typeof AuthenticatedMailboxesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMailboxesRoute: AuthenticatedMailboxesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgentEmailsRoute: ApiPublicAgentEmailsRoute,
  ApiPublicAgentPingRoute: ApiPublicAgentPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
